### ISSUE TITLE
来个服务间调用鉴权？

### ISSUE THREAD

**Issue by Lvbuqing** [qjyn1314/authorization-life#2]

**Comment by qjyn1314** [comment]
接口在A服务, A服务中已经获取到了当前登录用户的信息.
场景:A服务使用dubbo调用B服务, B服务也需要使用到当前登录用户的信息.
这个时候A服务如何将当前登录用户的信息透传给B服务?
1.在接口增加传参, 将当前登录用户的信息作为参数进行传递.
2.扩展dubbo的filter, 在filter中增加当前登录用户信息的传递.

后续此工程中会实现第二种方式.

上述描述是我理解的服务之间的调用的鉴权,是将当前登录用户的信息在此次请求中让其他服务也获取到同一个当前登录用户, 因为dubbo之间的调用,已经是服务内部之间的调用了, 并不需要鉴权此接口是否具备请求权限.
也参考了: https://cloud.tencent.com/developer/article/1661115

dubbo调用服务,dubbo也提供了token的认证, 这种认证是 procider提供的, 是指在调用服务的时候必须通过注册中心进行调用.

如果上述不是问题的答案, 还请将问题描述的更具体一些.

**Comment by Lvbuqing** [comment]
你这不是使用的spring cloud -alibaba，不应该使用springcloud全家桶么，咋又使用了dubbo....i😂😂😂

**Comment by qjyn1314** [comment]
原来你这是没看项目源码啊, 那你这是在干啥? 捋不清了?
